---
name: Test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, '3.10', 3.12]
        include:
          - os: ubuntu-20.04
            python-version: 3.6
          - os: macos-latest
            python-version: 3.x
          - os: windows-latest
            python-version: 3.x
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install -U wheel toml setuptools
      - run: pip install -e . -r tests/requirements.txt

      - name: Compile
        run: python setup.py build

      - name: Test
        run: pytest

      # Test PyInstaller.
      - run: pip uninstall -y rockhopper && pip install .
      - run: pip install pyinstaller
      - working-directory: tests/PyInstaller_
        run: pyinstaller frozen-pytest.spec
        if: ${{ matrix.python-version != 3.6 }}
      - working-directory: tests/PyInstaller_
        run: ./dist/frozen-pytest/frozen-pytest ../..
        if: ${{ matrix.python-version != 3.6 }}

      # Test old versions of dependencies. Should these fail, re-pin to working
      # versions both here and in the pyproject.toml
      - run: |
          pip install numpy==1.16.0 cslug==0.1.0 &&
          pytest
        if: ${{ matrix.python-version == 3.6 }}
